title: NoteTheme2
description: Advanced theme for note taking
baseurl: ""
url: ""

title-separator: "-"

google_analytics:
fb_app_id:

timezone: "Europe/Paris"
markdown: kramdown
mathjax: true
kramdown:
  input: GFM
highlighter: rouge
permalink: /:title

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-katex
  - jekyll-admin
  - jekyll-include-cache
  
sass:
  style: compact

exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME

